"""scoring

Revision ID: c0c5aa4cc3a1
Revises: d759b712e750
Create Date: 2025-12-17 12:12:39.153750
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c0c5aa4cc3a1'
down_revision = 'd759b712e750'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_players',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_snapshots',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_index', sa.Integer(), nullable=False),
    sa.Column('current_entry_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quiz_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('question_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active_quiz_index', sa.Integer(), nullable=True),
    sa.Column('active_question_index', sa.Integer(), nullable=True),
    sa.Column('current_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_answers',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['session_players.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'questions',
        sa.Column('scoring_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='exact'),
    )
    # Optional: drop the server default after backfilling existing rows
    op.alter_column('questions', 'scoring_type', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'scoring_type')
    op.drop_table('session_answers')
    op.drop_table('session_snapshots')
    op.drop_table('session_players')
    # ### end Alembic commands ###
